const FIELD_WIDTH = 1440;
const FIELD_HEIGHT = FIELD_WIDTH * 0.55;
const MIDDLE_CIRCLE_RATIO = 0.2;

const GOAL_ZONE_HEIGHT_RATIO = 0.3;
const GOAL_ZONE_WIDTH_RATIO = 0.1;

export default {
  FIELD_WIDTH,
  FIELD_HEIGHT,
  MIDDLE_CIRCLE_RATIO,
  GOAL_ZONE_HEIGHT_RATIO,
  GOAL_ZONE_WIDTH_RATIO,
};
