const FIELD_WIDTH = 1440;
const FIELD_HEIGHT = FIELD_WIDTH * 0.55;
const MIDDLE_CIRCLE_RATIO = 0.2;
const CORNER_ARC = FIELD_WIDTH * MIDDLE_CIRCLE_RATIO * 0.05;
const GRID_SPACING = 75;

export default {
  FIELD_WIDTH,
  FIELD_HEIGHT,
  MIDDLE_CIRCLE_RATIO,
  CORNER_ARC,
  GRID_SPACING,
};
