const FIELD_WIDTH = 1440;
const FIELD_HEIGHT = FIELD_WIDTH * 0.55;
const MIDDLE_CIRCLE_RATIO = 0.2;
const CORNER_ARC = FIELD_WIDTH * MIDDLE_CIRCLE_RATIO * 0.05;
const GRID_SPACING = 75;

const PENALTY_AREA_HEIGHT_RATIO = 0.6;
const PENALTY_AREA_WIDTH_RATIO = 0.16;

const GOAL_AREA_HEIGHT_RATIO = 0.4;
const GOAL_AREA_WIDTH_RATIO = 0.08;

const GOAL_ZONE_HEIGHT_RATIO = 0.3;
const GOAL_ZONE_WIDTH_RATIO = 0.1;

export default {
  FIELD_WIDTH,
  FIELD_HEIGHT,
  MIDDLE_CIRCLE_RATIO,
  CORNER_ARC,
  GRID_SPACING,
  PENALTY_AREA_HEIGHT_RATIO,
  PENALTY_AREA_WIDTH_RATIO,
  GOAL_ZONE_HEIGHT_RATIO,
  GOAL_ZONE_WIDTH_RATIO,
  GOAL_AREA_HEIGHT_RATIO,
  GOAL_AREA_WIDTH_RATIO,
};
