const SIZE = 40;
const NAMETAG_GAP = 15;

const BUBBLE_POINTER_SIZE = 10;
const BUBBLE_POINTER_OFFSET = 30;
const BUBBLE_CORNER_RADIUS = 10;

export default {
  SIZE,
  NAMETAG_GAP,

  BUBBLE_POINTER_SIZE,
  BUBBLE_POINTER_OFFSET,
  BUBBLE_CORNER_RADIUS,
};
