import { readdirSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Renames emoji assets to kebab-case slugs, dropping a trailing "256".
// e.g. "Cold Face 256.png" -> "cold-face.png"
const dir = join(import.meta.dir, "..", "apps", "client", "public", "emojis");

const slugify = (name: string): string =>
  name
    .replace(/\.[^.]+$/, "") // strip extension
    .replace(/\s*256\s*$/i, "") // drop trailing "256"
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

let renamed = 0;
for (const file of readdirSync(dir)) {
  const ext = file.match(/\.(png|svg|webp)$/i)?.[0]?.toLowerCase();
  if (!ext) continue;
  const target = `${slugify(file)}${ext}`;
  if (target === file) continue;
  renameSync(join(dir, file), join(dir, target));
  console.log(`${file}  ->  ${target}`);
  renamed++;
}
console.log(`\nDone. Renamed ${renamed} file(s).`);

// Emit a slug manifest shared by client + server, so the catalog isn't a
// hand-written array. Re-run this whenever emojis are added/removed.
const slugs = readdirSync(dir)
  .filter((f) => /\.png$/i.test(f))
  .map((f) => f.replace(/\.png$/i, ""))
  .sort();
const manifest = join(
  import.meta.dir,
  "..",
  "packages",
  "shared",
  "src",
  "emoji-slugs.ts",
);
writeFileSync(
  manifest,
  `// AUTO-GENERATED by scripts/slugify-emojis.ts — do not edit by hand.\n` +
    `export const EMOJI_SLUGS = ${JSON.stringify(slugs, null, 2)} as const;\n`,
);
console.log(
  `Wrote ${slugs.length} slugs to packages/shared/src/emoji-slugs.ts`,
);
